import { Footer } from "@/components/Footer";
import { NavBar } from "@/components/NavBar";
import { Montserrat } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"], variable: "--font-mont" });

export const metadata = {
  title: "Antonio Santos Portfólio",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  const cookieStore = cookies();
  const cookieTheme = cookieStore.get("@AS-theme");
  const theme = cookieTheme?.value;

  return (
    <html lang="pt-br" className={`${theme && theme === "dark" ? theme : ""}`}>
      <body
        className={`${montserrat.className} bg-light dark:bg-dark w-full min-h-screen`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
